README.md

Update README.md with setup-obs command + standardized punctuation

---

extensions/cloudformation-templates/livestream-workflow.json.ejs
extensions/livestream-defaults.json
extensions/livestream-push.js
extensions/livestream-questions.json

#2 
- set resourcename to 'mylivestream' by default instead of project name
- put GOP settings behind an 'advanced prompt' using 'choice'
- fixed some typos in livestream-push
- removed defaultQuestions dict, replaced advancedQuestions

fixed typos, added advanced prompt

---

package.json
scripts/post-install.js

*Issue #, if available:* #45 
*Description of changes:* Adds postinstall script

Postinstall

---

.github/workflows/nodejs.yml

*Issue #, if available:* #33 
*Description of changes:* 
- Getting started on my unit tests

Added lint tester for pull requests

---

provider-utils/awscloudformation/templates/Amplify_Video_Ott_Hls_Ts_Avc_Aac.json

Changed template name

---

provider-utils/awscloudformation/service-walkthroughs/vod-push.js

change default resource name for vod resource to avoid 

change default resource name

---

README.md
live-quickstart.md

This is part of #35 - just wanted to get it added ASAP
Adds live streaming quickstart to amplify video docs

simplified readme, added live streaming quickstart

---

provider-utils/awscloudformation/cloudformation-templates/vod-helpers/CFDistribution.template.ejs
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/LambdaFunctions/OutputLambda/index.js.ejs
provider-utils/awscloudformation/cloudformation-templates/vod-workflow.yaml.ejs
provider-utils/awscloudformation/schemas/schema.graphql.ejs
provider-utils/awscloudformation/service-walkthroughs/vod-push.js
provider-utils/vod-questions.json

*Issue #, if available:* #68 
*Description of changes:* Adds support for non-signed urls to be used with cloudfront

Added support for non-signed urls

---

.eslintignore
package-lock.json
package.json
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/InputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/LambdaFunctions/InputLambda/index.js
provider-utils/awscloudformation/service-walkthroughs/vod-push.js

*Description of changes:* fixes issue with no cdn deploy

Added fix for no cdn deploys

---

provider-utils/awscloudformation/index.js
provider-utils/vod-questions.json

Fix #76
Fix #77 
*Description of changes:* Fixes two minor issues

Minor quality of life updates

---

package-lock.json
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/LambdaFunctions/OutputLambda/index.js.ejs

*Description of changes:* Fixes bad lambda

Fix output artifact

---

README.md

adding link to blog post

---

CONTRIBUTING.md
README.md

contribution guide and minor readme updates

---

package-lock.json
package.json
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/LambdaFunctions/CloudFrontTokenGen/index.js
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/LambdaFunctions/InputLambda/index.js
provider-utils/awscloudformation/default-values/vod-defaults.json
provider-utils/awscloudformation/service-walkthroughs/vod-push.js
provider-utils/vod-questions.json

Fixes #65 
Fixes #84 
*Description of changes:* Adds check to see if mediaconvert is already configured and adds prompts to override schema

Adds some small bug fixes

---

README.md

fixes part of #35 
simple readme

readme streamline

---

provider-utils/awscloudformation/service-walkthroughs/vod-push.js
provider-utils/awscloudformation/templates/Amplify_Video_HLS.json
provider-utils/awscloudformation/templates/Amplify_Video_System_Accelerated_Ott_Hls_Ts_Avc_Aac.json
provider-utils/awscloudformation/templates/Amplify_Video_System_Ott_Hls_Ts_Avc_Aac.json

added default hls template

---

provider-utils/awscloudformation/cloudformation-templates/vod-helpers/LambdaFunctions/InputLambda/index.js

decode uri fix

---

package-lock.json
package.json
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/CFTokenGen.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/InputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/OutputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/S3TriggerSetup.template
provider-utils/awscloudformation/cloudformation-templates/vod-workflow.yaml.ejs
provider-utils/awscloudformation/index.js
provider-utils/awscloudformation/utils/video-staging.js
provider-utils/supported-services.json
provider-utils/vod-questions.json

*Issue #, if available:* 
Fixes #101 
Adds hash to lambda's uploaded to S3 so we can detect changes.

Added hashes to lambdas

---

commands/video.js
commands/video/setup-obs.js
provider-utils/awscloudformation/index.js
provider-utils/awscloudformation/service-walkthroughs/vod-push.js
provider-utils/awscloudformation/utils/get-aws.js
provider-utils/awscloudformation/utils/livestream-obs.js
provider-utils/awscloudformation/utils/video-getinfo.js
provider-utils/awscloudformation/utils/video-staging.js

*Issue #, if available:* Fixes #25
- Replaces most instances of `console.log` with an appropriate variant of `context.print` (functionality provided by Amplify). 
- Some prompts were slightly changed to better reflect their intent.

Standardize logging methods and messages

---

package-lock.json
package.json
provider-utils/awscloudformation/utils/video-staging.js

*Description of changes:* Fixes issue with custom lambdas not looking in the right place

Fixed custom lambdas not pushing correctly

---

commands/video/start.js
commands/video/stop.js
package-lock.json
package.json
provider-utils/awscloudformation/index.js
provider-utils/awscloudformation/utils/livestream-startstop.js

*Issue #, if available:* #1 
*Description of changes:* Adds new way to start and stop stream. This is preparing for CloudFormation refactor release

Added new way for start stop

---

commands/video/setup-obs.js
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/IVS-Channel.template
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/IVS-Custom.template
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/LambdaFunctions/IVSShim/index.js
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/LambdaFunctions/IVSShim/package-lock.json
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/LambdaFunctions/IVSShim/package.json
provider-utils/awscloudformation/cloudformation-templates/ivs-workflow-template.yaml.ejs
provider-utils/awscloudformation/service-walkthroughs/ivs-push.js
provider-utils/awscloudformation/utils/livestream-obs.js
provider-utils/awscloudformation/utils/video-getinfo.js
provider-utils/awscloudformation/utils/video-staging.js
provider-utils/ivs-questions.json
provider-utils/supported-services.json

*Issue #, if available:* n/a
*Description of changes:* 
- Adding support for beta support IVS
- More features coming soon

Adding support to new AWS Service

---

package-lock.json
package.json
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/IVS-Channel.template
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/LambdaFunctions/IVSShim/index.js
provider-utils/awscloudformation/cloudformation-templates/ivs-workflow-template.yaml.ejs
provider-utils/awscloudformation/service-walkthroughs/ivs-push.js
provider-utils/ivs-questions.json

*Issue #, if available:*n/a
*Description of changes:* Added more questions for IVS

Added more parameters

---

package-lock.json
package.json
provider-utils/awscloudformation/cloudformation-templates/ivs-helpers/IVS-Custom.template
provider-utils/awscloudformation/cloudformation-templates/ivs-workflow-template.yaml.ejs
provider-utils/awscloudformation/utils/video-getinfo.js

*Issue #, if available:* Fixes #133 
- Adds custom names to lambda and IVS stream
- Timeout increase on lambda

IVS Name fix

---

package-lock.json
package.json
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/InputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/OutputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/S3InputBucket.template.ejs
provider-utils/awscloudformation/cloudformation-templates/vod-workflow-template.yaml.ejs
provider-utils/awscloudformation/schemas/schema.graphql.ejs
provider-utils/awscloudformation/service-walkthroughs/vod-push.js
provider-utils/vod-questions.json

*Issue #, if available:* Fixes #136 
*Description of changes:* Adds new permission model. If they select Any it will allow any Auth user to run S3 put!

Added new permissions model

---

package-lock.json
package.json
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/InputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/OutputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-workflow-template.yaml.ejs
provider-utils/awscloudformation/service-walkthroughs/vod-push.js

*Issue #, if available:* n/a
Adds GraphQL API endpoint and ID to our lambda functions environment variable.

Adding graghql endpoint and apiid to dependencies

---

provider-utils/ivs-questions.json
provider-utils/supported-services.json

No issue
Added full service name to resource list (AWS Elemental, Amazon Interactive Video, etc)
Updated IVS prompts to improve consistency with UI and provide a little bit  of latency context

minor changes to IVS question flow

---

provider-utils/awscloudformation/cloudformation-templates/livestream-helpers/LambdaFunctions/psdemo-js-live-workflow_v0.4.0/resources/uhd.json
provider-utils/awscloudformation/cloudformation-templates/livestream-helpers/medialive-channel.template
provider-utils/awscloudformation/cloudformation-templates/livestream-helpers/medialive.template
provider-utils/awscloudformation/cloudformation-templates/livestream-workflow-template.json.ejs
provider-utils/livestream-questions.json

added UHD option for live encoding

---

package-lock.json
package.json
provider-utils/awscloudformation/service-walkthroughs/vod-push.js

*Issue #, if available:* Fixes #159 

Fixes #159

---

provider-utils/vod-questions.json

#170 
updated question to explicitly ask for access key ID

specified access key id explicitly

---

provider-utils/awscloudformation/utils/livestream-obs.js

Reverts awslabs/amplify-video#183

Revert "Fix OBS setup which create wrong stream URL"

---

.eslintrc.json
.github/workflows/jest.yml
CONTRIBUTING.md
__mocks__/sum-sample.js
package-lock.json
package.json
tests/sum.test.js

*Issue #186*
This PR adds a new workflow file in `.github/workflows` to run Jest tests suite
It has been tested locally using [act](https://github.com/nektos/act)

Add a Github Action to trigger Jest tests

---

provider-utils/awscloudformation/cloudformation-templates/vod-helpers/CFDistribution.template.ejs

Fixed CloudFront origin request issues

---

.eslintignore

.eslintignore adding tests

---

provider-utils/awscloudformation/cloudformation-templates/vod-helpers/LambdaFunctions/SetupTriggerLambda/index.js
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/S3TriggerSetup.template

*Issue #, if available:* Fixes #240
Adds a way to set custom triggers. Makes the process easier to use and makes it so that you don't have to change the lambda function

Custom S3 Triggers

---

tests/integration/vod.test.js

Adding region for tests

---

tests/integration/cloudformation.test.js

Added Region to CloudFormation test

---

package-lock.json

*Issue #, if available:* n/a
*Description of changes:* Vuln patching

Security Patches

---

provider-utils/awscloudformation/cloudformation-templates/livestream-helpers/lambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/CFTokenGen.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/InputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/OutputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/S3TriggerSetup.template

*Issue #, if available:* Fixes #266
*Description of changes:* 
Upgrades all node version to 14.x 

Upgrading all lambda to Node14.x

---

.github/workflows/jest.yml
.github/workflows/nodejs.yml
package.json
provider-utils/awscloudformation/cloudformation-templates/livestream-helpers/lambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/CFTokenGen.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/InputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/OutputTriggerLambda.template
provider-utils/awscloudformation/cloudformation-templates/vod-helpers/S3TriggerSetup.template

Due to 10.x being deprecated soon we are moving tests to 12.x and 14.x to prepare for supporting these new versions.

Move test versions to 12.x and 14.x 

---

provider-utils/awscloudformation/service-walkthroughs/livestream-push.js

*Description of changes:* Fixes Livestream not having a valid name on new project create

Fix livestream issues

---

package-lock.json

Security patching

---

package.json
provider-utils/awscloudformation/cloudformation-templates/vod-workflow-template.yaml.ejs

*Description of changes:* Fixes small bugs and tests up

Fix release bugs

---

.github/workflows/jest.yml
package-lock.json
package.json
provider-utils/awscloudformation/default-values/vod-defaults.json
provider-utils/awscloudformation/service-walkthroughs/vod-push.js
provider-utils/vod-questions.json

Hlsdefault

---

provider-utils/awscloudformation/cloudformation-templates/vod-helpers/S3OutputBucket.template

Remove extra single quote from policy in S3OutputBucket.template file  

fix(S3OutuputBucketCFTemplate): Remove extra single quote from ARN

---

provider-utils/awscloudformation/service-walkthroughs/vod-push.js

*Description of changes:* Fix an issue with Dash changes that made custom templates unusable.

Fix issue with custom templates not working

---

provider-utils/awscloudformation/cloudformation-templates/vod-helpers/S3OutputBucket.template

Fixed S3AuthGet:

---

provider-utils/awscloudformation/cloudformation-templates/vod-helpers/SnsSetup.template.ejs
provider-utils/awscloudformation/cloudformation-templates/vod-workflow-template.yaml.ejs

fix for bug 312
